services:
  drawio:
    image: jgraph/drawio:29.3.6
    container_name: drawio
    ports:
      - "8080:8080"
    volumes:
      - drawio_data:/root/.drawio
    restart: no
    environment:
      - VIRTUAL_HOST=drawio.local
      - VIRTUAL_PORT=8080
    networks:
      - drawio_network

volumes:
  drawio_data:

networks:
  drawio_network:
    driver: bridge
