services:
  metabase:
    image: metabase/metabase:v0.62.3.5
    container_name: metabase
    restart: no
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: root
      MB_DB_HOST: postgres
      JAVA_TIMEZONE: America/Sao_Paulo

    volumes:
      - ./metabase-entrypoint.sh:/metabase-entrypoint.sh

    entrypoint: ["/bin/sh", "/metabase-entrypoint.sh"]

    networks:
      - postgres-network

networks:
  postgres-network:
    external: true
    name: postgresql_postgres-network