services:
  localstack:
    container_name: "localstack-terraform"
    image: localstack/localstack:4.7.0
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
      - "8080:8080"  # Porta para acessar a Web UI
    environment:
    - DEBUG=1
    - SERVICES=s3,dynamodb,lambda,sns,sqs
    - AWS_ACCESS_KEY_ID=test
    - AWS_SECRET_ACCESS_KEY=test
    - LOCALSTACK_AUTH_TOKEN=test
    - AWS_DEFAULT_REGION=us-east-1
    - SQS_ENDPOINT_STRATEGY=domain
    - S3_ADDRESSING_STYLE=path
    - LOCALSTACK_HOST=localstack
    - HOSTNAME_EXTERNAL=localstack
    - LS_MAIN_CONTAINER_ADVERTISE_EXTERNAL_URL=http://localstack:4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./docker-entrypoint.sh:/etc/localstack/init/ready.d/10-bootstrap.sh:ro
    networks:
      - localstack_network

  terraform:
    image: hashicorp/terraform:1.14.4
    container_name: terraform
    volumes:
      - ./terraform:/terraform
      - ~/.aws:/root/.aws  # Para usar as credenciais AWS locais
    working_dir: /terraform
    entrypoint: ["sh", "-c", "terraform init && terraform apply -auto-approve && tail -f /dev/null"]
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack
    networks:
      - localstack_network

networks:
  localstack_network:
    driver: bridge
