ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
--DROP USER PRODUCT CASCADE;  
CREATE USER PRODUCT IDENTIFIED BY PRODUCT;
GRANT UNLIMITED TABLESPACE TO PRODUCT WITH ADMIN OPTION;
ALTER SESSION SET CURRENT_SCHEMA=PRODUCT;

