services:
  angular:
    image: node:24.13.1  # Usando a imagem oficial do Node.js 24.13.1
    container_name: angular-app
    working_dir: /app/hello-world  # Diretório do projeto Angular dentro do contêiner
    volumes:
      - ./app:/app  # Mapeia o diretório app local para o contêiner
    ports:
      - "4200:4200"  # Mapear a porta 4200 para acessar o Angular localmente
    command: sh -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0 --disable-host-check"  # Instalar Angular CLI e rodar o servidor
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge
