services:
  superset_app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: superset_app
    restart: no
    ports:
      - "8088:8088"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: superset

      SUPERSET_SECRET_KEY: "x9K2mP8vQ4zT7wL1cR6sN3bJ8hG5fD2aA9zX1cV7bM"
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:root@host.docker.internal:5432/superset

    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh

    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    networks:
      - postgres-network
networks:
  postgres-network:
    external: true
    name: postgresql_postgres-network