services:
  mysql:
    image: mysql:9.5.0
    container_name: mysql
    restart: no
    environment:
      - MYSQL_DATABASE=myapp_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - mysql

volumes:
  mysql-volume:
    driver: local
